// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(4194227654);
}

export function SetSystemProxy(enable: boolean, listen: string, routingMode: string): $CancellablePromise<string> {
    return $Call.ByID(2834409808, enable, listen, routingMode);
}

export function StartWorker(server: string, listen: string, token: string, ip: string, dns: string, ech: string, routingMode: string): $CancellablePromise<string> {
    return $Call.ByID(940670875, server, listen, token, ip, dns, ech, routingMode);
}

export function StopWorker(): $CancellablePromise<void> {
    return $Call.ByID(2738107153);
}
