// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkerService 是 Wails 服务层的核心结构体，负责代理进程的生命周期管理。
 * 通过 Wails 的 Service 机制与前端通信，控制代理的启动和停止。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * IsRunning 返回代理是否正在运行。
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(4194227654);
}

/**
 * StartWorker 启动代理核心服务。通过 Wails 前端调用，传入用户配置的各种参数。
 * 返回空字符串表示成功启动，否则返回错误信息。
 */
export function StartWorker(server: string, tunName: string, token: string, ip: string, dns: string, ech: string, routingMode: string): $CancellablePromise<string> {
    return $Call.ByID(940670875, server, tunName, token, ip, dns, ech, routingMode);
}

/**
 * StopWorker 停止正在运行的代理核心服务，并更新托盘菜单状态。
 */
export function StopWorker(): $CancellablePromise<void> {
    return $Call.ByID(2738107153);
}
